WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 780
FPS = 60
AUTO_VISUAL_REPORT_SECONDS = None

TOP_HUD_HEIGHT = 86
BOTTOM_HUD_HEIGHT = 154
LANE_COUNT = 5
COLUMN_COUNT = 7

FIELD_TOP = TOP_HUD_HEIGHT
FIELD_BOTTOM = WINDOW_HEIGHT - BOTTOM_HUD_HEIGHT
FIELD_HEIGHT = FIELD_BOTTOM - FIELD_TOP
LANE_HEIGHT = FIELD_HEIGHT / LANE_COUNT

BASE_LINE_X = 112
TILE_START_X = 190
TILE_GAP = 14
TILE_WIDTH = 112
TILE_HEIGHT = 76
