import os


TOP_BAR_HEIGHT = 88
BOTTOM_BAR_HEIGHT = 180
LANE_COUNT = 5
COLUMN_COUNT = 7
MAX_WAVES = 12
FRAMES_PER_SECOND = 60
WAVE_DELAY_SECONDS = 5
SOUND_DIR = os.path.join(os.path.dirname(__file__), "sounds")

UNIT_TYPES = [
    {
        "name": "Soldier",
        "cost": 45,
        "base_damage": 10,
        "base_range": 180,
        "base_fire_rate": 20,
        "projectile_speed": 15,
        "max_hp": 100,
        "color": "#3b82f6",
        "accent": "#dbeafe",
        "upgrade_cost": 22,
        "projectile_color": "#dbeafe",
        "short": "Burst fire",
        "ability": "burst",
    },
    {
        "name": "Hunter",
        "cost": 58,
        "base_damage": 16,
        "base_range": 230,
        "base_fire_rate": 32,
        "projectile_speed": 17,
        "max_hp": 75,
        "color": "#22c55e",
        "accent": "#dcfce7",
        "upgrade_cost": 28,
        "projectile_color": "#bbf7d0",
        "short": "Slows runners",
        "ability": "slow",
    },
    {
        "name": "Sniper",
        "cost": 72,
        "base_damage": 30,
        "base_range": 340,
        "base_fire_rate": 54,
        "projectile_speed": 20,
        "max_hp": 68,
        "color": "#a855f7",
        "accent": "#f3e8ff",
        "upgrade_cost": 36,
        "projectile_color": "#e9d5ff",
        "short": "Piercing",
        "ability": "pierce",
    },
    {
        "name": "Flamethrower",
        "cost": 68,
        "base_damage": 8,
        "base_range": 130,
        "base_fire_rate": 8,
        "projectile_speed": 11,
        "max_hp": 110,
        "color": "#f97316",
        "accent": "#ffedd5",
        "upgrade_cost": 32,
        "projectile_color": "#fdba74",
        "short": "Area burn",
        "ability": "splash",
    },
    {
        "name": "Engineer",
        "cost": 82,
        "base_damage": 18,
        "base_range": 200,
        "base_fire_rate": 26,
        "projectile_speed": 14,
        "max_hp": 125,
        "color": "#eab308",
        "accent": "#fef9c3",
        "upgrade_cost": 40,
        "projectile_color": "#fde68a",
        "short": "Repairs allies",
        "ability": "repair",
    },
]

ENEMY_TYPES = [
    {
        "name": "Walker",
        "kind": "Zombie",
        "color": "#84cc16",
        "accent": "#d9f99d",
        "base_hp": 56,
        "speed": 1.1,
        "damage": 10,
        "attack_rate": 40,
        "reward": 14,
        "radius": 20,
        "shape": "walker",
        "armor": 0,
    },
    {
        "name": "Runner",
        "kind": "Zombie",
        "color": "#22c55e",
        "accent": "#bbf7d0",
        "base_hp": 42,
        "speed": 1.85,
        "damage": 7,
        "attack_rate": 28,
        "reward": 12,
        "radius": 16,
        "shape": "runner",
        "armor": 0,
    },
    {
        "name": "Brute",
        "kind": "Brute",
        "color": "#4d7c0f",
        "accent": "#ecfccb",
        "base_hp": 92,
        "speed": 0.85,
        "damage": 16,
        "attack_rate": 52,
        "reward": 20,
        "radius": 25,
        "shape": "brute",
        "armor": 2,
    },
    {
        "name": "Armored",
        "kind": "Brute",
        "color": "#475569",
        "accent": "#e2e8f0",
        "base_hp": 78,
        "speed": 1.0,
        "damage": 13,
        "attack_rate": 44,
        "reward": 18,
        "radius": 22,
        "shape": "armored",
        "armor": 5,
    },
    {
        "name": "Medic",
        "kind": "Zombie",
        "color": "#14b8a6",
        "accent": "#ccfbf1",
        "base_hp": 64,
        "speed": 1.2,
        "damage": 8,
        "attack_rate": 42,
        "reward": 19,
        "radius": 19,
        "shape": "medic",
        "armor": 0,
        "heal": 0.35,
    },
]
